export const translations = {
    en: {
        "nav.home": "Home",
        "nav.about": "About",
        "nav.cv": "CV",
        "nav.portfolio": "Portfolio",
        "nav.contact": "Contact",
        "footer.rights": "All rights reserved.",
        "hero.greeting": "Hello, I am",
        "hero.role": "Creative Developer & Designer",
        "hero.bio": "I craft accessible, pixel-perfect, and minimalist web experiences using modern standards.",
        "hero.cta": "View My Work",
        "btn.portfolio": "View Portfolio",
        "btn.contact": "Contact Me",
        "about.title": "About Me",
        "about.bio": "I am a dedicated web developer with a focus on minimalism and performance. I believe that good design is as little design as possible. My work bridges the gap between functional logic and aesthetic detail.",
        "about.skills": "Skills & Technologies",
        "about.edu": "Education",
        "cv.title": "Curriculum Vitae",
        "cv.download": "Print / Save PDF",
        "cv.exp": "Experience",
        "cv.edu": "Education",
        "cv.skills": "Skills",
        "cv.contact": "Contact",
        "port.title": "Selected Works",
        "port.view": "View Project",
        "port.code": "View Code",
        "contact.title": "Get In Touch",
        "contact.name": "Name",
        "contact.email": "Email",
        "contact.message": "Message",
        "contact.submit": "Send Message",
        "contact.social": "Socials"
    },
    tr: {
        "nav.home": "Anasayfa",
        "nav.about": "Hakkımda",
        "nav.cv": "CV",
        "nav.portfolio": "Portfolyo",
        "nav.contact": "İletişim",
        "footer.rights": "Tüm hakları saklıdır.",
        "hero.greeting": "Merhaba, Ben",
        "hero.role": "Yaratıcı Geliştirici & Tasarımcı",
        "hero.bio": "Modern standartları kullanarak erişilebilir, piksel mükemmelliğinde ve minimalist web deneyimleri yaratıyorum.",
        "hero.cta": "Çalışmalarımı Gör",
        "btn.portfolio": "Portfolyoyu Gör",
        "btn.contact": "Bana Ulaş",
        "about.title": "Hakkımda",
        "about.bio": "Minimalizm ve performansa odaklanan tutkulu bir web geliştiricisiyim. İyi tasarımın mümkün olduğunca az tasarım olduğuna inanıyorum. Çalışmalarım, fonksiyonel mantık ile estetik detay arasındaki köprüyü kurar.",
        "about.skills": "Yetenekler & Teknolojiler",
        "about.edu": "Eğitim",
        "cv.title": "Özgeçmiş",
        "cv.download": "Yazdır / PDF Kaydet",
        "cv.exp": "Deneyim",
        "cv.edu": "Eğitim",
        "cv.skills": "Yetenekler",
        "cv.contact": "İletişim",
        "port.title": "Seçilmiş İşler",
        "port.view": "Projeyi Gör",
        "port.code": "Kodu İncele",
        "contact.title": "İletişime Geç",
        "contact.name": "İsim",
        "contact.email": "E-posta",
        "contact.message": "Mesaj",
        "contact.submit": "Mesaj Gönder",
        "contact.social": "Sosyal Medya"
    }
};
