export const translations = {
    en: {
        "nav.home": "Home",
        "nav.about": "About",
        "nav.cv": "CV",
        "nav.portfolio": "Portfolio",
        "nav.contact": "Contact",
        "footer.rights": "All rights reserved.",
        "hero.greeting": "Hello, I am",
        "hero.role": "Software Engineering Student & Creative Designer",
        "hero.bio": "Merging analytical technology with artistic expression to build innovative, high-quality digital experiences.",
        "hero.cta": "View My Work",
        "btn.portfolio": "View Portfolio",
        "btn.contact": "Contact Me",
        "about.title": "About Me",
        "about.bio": "I am a creative professional bridging the gap between visual arts and software engineering. with a strong foundation in design and a growing technical expertise, I bring a unique, artistic perspective to analytical projects.",
        "about.skills": "Skills & Technologies",
        "about.edu": "Education",
        "cv.title": "Curriculum Vitae",
        "cv.print": "Print / Save PDF",
        "cv.downloadFile": "Download CV",
        "cv.close": "Close",
        "cv.exp": "Experience",
        "cv.edu": "Education",
        "cv.skills": "Skills",
        "cv.contact": "Contact",
        "port.title": "Selected Works",
        "port.view": "View Project",
        "port.code": "View Code",
        "contact.title": "Get In Touch",
        "contact.name": "Name",
        "contact.email": "Email",
        "contact.message": "Message",
        "contact.submit": "Send Message",
        "contact.social": "Socials"
    },
    tr: {
        "nav.home": "Anasayfa",
        "nav.about": "Hakkımda",
        "nav.cv": "CV",
        "nav.portfolio": "Portfolyo",
        "nav.contact": "İletişim",
        "footer.rights": "Tüm hakları saklıdır.",
        "hero.greeting": "Merhaba, Ben",
        "hero.role": "Yazılım Mühendisliği Öğrencisi & Yaratıcı Tasarımcı",
        "hero.bio": "Analitik teknolojiyi sanatsal ifadeyle birleştirerek yenilikçi, yüksek kaliteli dijital deneyimler oluşturuyorum.",
        "hero.cta": "Çalışmalarımı Gör",
        "btn.portfolio": "Portfolyoyu Gör",
        "btn.contact": "Bana Ulaş",
        "about.title": "Hakkımda",
        "about.bio": "Minimalizm ve performansa odaklanan tutkulu bir web geliştiricisiyim. İyi tasarımın mümkün olduğunca az tasarım olduğuna inanıyorum. Çalışmalarım, fonksiyonel mantık ile estetik detay arasındaki köprüyü kurar.",
        "about.skills": "Yetenekler & Teknolojiler",
        "about.edu": "Eğitim",
        "cv.title": "Özgeçmiş",
        "cv.print": "Yazdır / PDF Kaydet",
        "cv.downloadFile": "CV İndir",
        "cv.close": "Kapat",
        "cv.exp": "Deneyim",
        "cv.edu": "Eğitim",
        "cv.skills": "Yetenekler",
        "cv.contact": "İletişim",
        "port.title": "Seçilmiş İşler",
        "port.view": "Projeyi Gör",
        "port.code": "Kodu İncele",
        "contact.title": "İletişime Geç",
        "contact.name": "İsim",
        "contact.email": "E-posta",
        "contact.message": "Mesaj",
        "contact.submit": "Mesaj Gönder",
        "contact.social": "Sosyal Medya"
    }
};
